.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH DANGERDEEP 6 "FEBRUARY 2004" Linux "User Manuals"
.SH NAME
dangerdeep \- World War II German submarine simulator
.SH SYNOPSIS
.B foo [--res
.I n
.B ] [--nofullscreen ]
.B [--nosound ]
.B [--help ]
.SH DESCRIPTION
.B dangerdeep
Danger from the Deep is a World War II German submarine simulator game.
The game has custom and historical missions, three submarines,
three warship and eight civilian ship types.

It's state is alpha but it is playable.
.SH OPTIONS
.IP "--res n"
use 
.I n
as the  horizontal resolution. 
.I n
is 512,640,800,1024 (recommended) or 1280.
.IP "--nofullscreen"
Use windowed mode instead of displaying full-screen.
.IP --nosound
Disable sound effects.
.IP "--help"
Displays brief usage information.
.SH FILES
.I /usr/share/games/dangerdeep/missions/
.RS
Directory containing custom missions. To add your own mission, you also need to add the name of your mission file in 
.I /usr/share/games/dangerdeep/missions/list 
.RE
.I ~/.dangerdeep/
.RS
Career and high score information. 
.SH BUGS
Possibly several. To report them, please see 
.I http://dangerdeep.sourceforge.net/contact.php
.SH AUTHOR
Thorsten Jordan <thorsten_jordan@gmx.de>
