#!/bin/bash
VERSION=0.0.18 # fixme get from SConstruct
TMP=.tmp
BASEDIR=dangerdeep-$VERSION
rm -rf $TMP
mkdir $TMP
mkdir $TMP/$BASEDIR
cp dangerdeep-$VERSION.tar.gz $TMP/$BASEDIR
cd $TMP/$BASEDIR
tar zxf dangerdeep-$VERSION.tar.gz
rm dangerdeep-$VERSION.tar.gz
cd ../..
cp build/win32/dangerdeep.exe $TMP/$BASEDIR
cp dlls/*.dll $TMP/$BASEDIR
mkdir $TMP/$BASEDIR/config
mkdir $TMP/$BASEDIR/save
mkdir $TMP/$BASEDIR/highscores
cd $TMP
rm -rf $BASEDIR/src
rm -rf $BASEDIR/build
zip -9r dangerdeep-$VERSION-win32.zip *
cd ..
mv $TMP/dangerdeep-$VERSION-win32.zip .
rm -rf $TMP
