#!/bin/bash
set -e

version=`awk '$1 ~ /Version/ { print $2 }' debian/DEBIAN/control`
arch=`awk '$1 ~ /Architecture/ { print $2 }' debian/DEBIAN/control`
debroot="dangerdeep_$version""_$arch"
debfile="dangerdeep_$version""_$arch.deb"
bindir='usr/games'
datadir='usr/share/games'
mandir='usr/share/man/man6'
docdir='usr/share/doc/dangerdeep'

#not needed any longer
#./configure --bindir=/$bindir --datadir=/$datadir && make clean && make || exit $?

mkdir -p $debroot && cp -R debian/* $debroot
for dir in DEBIAN $bindir $datadir/dangerdeep $mandir $docdir; do
	mkdir -p $debroot/$dir
done

# to compile and install it
scons installbindir=\#/$debroot/$bindir installdatadir=\#/$debroot/$datadir/dangerdeep datadir=/$datadir/dangerdeep install

#install -s src/dangerdeep $debroot/$bindir
#cp -Rf data/* $debroot/$datadir/dangerdeep

cp -f doc/man/*.[0-9] $debroot/$mandir
cp -f ChangeLog $debroot/$docdir/changelog
cp -fr doc/debian/[a-z]* $debroot/$docdir
rm -rf `find $debroot -name .sconsign`
rm -rf `find $debroot -name CVS`
rm -rf `find $debroot -name "SCons*"`
gzip -f --best $debroot/$mandir/*.[0-9]
gzip -f --best $debroot/$docdir/changelog
gzip -f --best $debroot/$docdir/changelog.Debian

find $debroot -type f -exec chmod 0644 \{\} \; -type d -exec chmod 0755 \{\} \;
chmod 755 $debroot/$bindir/dangerdeep

# remove debug symbols
strip -s $debroot/$bindir/dangerdeep

#rm `find $debroot -type f -and -name 'Makefile*'`

chmod -R a-s $debroot

chmod -R a-s $debroot

fakeroot dpkg-deb --build $debroot && \
	lintian $debfile && \
	echo "$debfile created"
rm -r $debroot
