#!/bin/bash
VERSION=0.0.18 # fixme get from SConstruct
TMP=.tmp
BASEDIR=dangerdeep-$VERSION
rm -rf $TMP
mkdir $TMP
mkdir $TMP/$BASEDIR
cp -r data $TMP/$BASEDIR
cp build/win32/dangerdeep.exe $TMP/$BASEDIR
cp dlls/*.dll $TMP/$BASEDIR
cd $TMP
DELETE1=`find . -name "Makefile*"`
DELETE2=`find . -name "CVS"`
DELETE3=`find . -name ".xvpics"`
rm -rf $DELETE1 $DELETE2 $DELETE3
zip -9r dangerdeep-$VERSION-win32.zip *
cd ..
mv $TMP/dangerdeep-$VERSION-win32.zip .
rm -rf $TMP
