#!/bin/bash
VERSION=`cat version`
mkdir .tmpbuild
cd .tmpbuild
bzip2 -d -c ../dangerdeep-$VERSION.tar.bz2 | tar x
cd dangerdeep-$VERSION
rm -rf src
rm -f *
rm -f `find . -name "Makefile*"`
cp ../../dangerdeep.exe .
cd ..
zip -r ../dangerdeep-$VERSION-win32.zip dangerdeep-$VERSION
cd ..
rm -rf .tmpbuild
