################ needed imports
import os
import sys

################ global config values
version = '0.0.20'

################ base paths (needed for Win32 OS)
sdlbase = 'd:\\sdl-devel\\SDL'
sdlimagebase = 'd:\\sdl-devel\\SDL_image'
sdlnetbase = 'd:\\sdl-devel\\SDL_net'
sdlmixerbase = 'd:\\sdl-devel\\SDL_mixer'
fftw3base = 'd:\\fftw3'
glbase = 'd:\\Dev-Cpp\\include\\gl'
# glbase = '/Microsoft Visual Studio/vc98/Include/gl/'

################ change base of dirs (unix OS)
installbindir = '/usr/local/bin'
installdatadir = '/usr/local/share/dangerdeep'
if ARGUMENTS.get('installbindir', 0):
	installbindir = ARGUMENTS.get('installbindir', 0)
if ARGUMENTS.get('installdatadir', 0):
	installdatadir = ARGUMENTS.get('installdatadir', 0)


################ set environment

osspecificsrc = []

fftwlib = 'fftw3'
if sys.platform == 'win32':
	print "Compiling for Win32 Environment"
	env = Environment(ENV = os.environ, tools = ['mingw'])
	env.Append(CPPPATH = [sdlbase + '\\include\\SDL', sdlimagebase + '\\include', sdlnetbase + '\\include', sdlmixerbase + '\\include', fftw3base, glbase])
	libpath = [sdlbase + '\\lib', sdlimagebase + '\\lib', sdlnetbase + '\\lib', sdlmixerbase + '\\lib', fftw3base]
	gllibs = ['opengl32', 'glu32']
	sdllibs = ['SDL', 'SDL_image']
	env.Append(CCFLAGS = '-Wall -O2 -D_REENTRANT') # for mingw!
	datadir = './data'
	build_dir = 'win32'
elif sys.platform == 'darwin':
	print "Compiling for MacOSX"
	env = Environment(ENV = os.environ)
	env.Append(CPPPATH = ['/System/Library/Frameworks/AGL.framework/Versions/A/Headers', '/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers', '/usr/include/SDL'])
	libpath = ['/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries', '/sw/lib', '/usr/local/lib', '/usr/lib']
	gllibs = []
	sdllibs = ['SDL', 'SDL_image']
	env.Append(CCFLAGS = '-Wall -g -O2 -fno-coalesce `sdl-config --cflags`')
	env.Append(LINKFLAGS = '-F/Library/Frameworks -framework AGL -framework OpenGL -framework GLUT -framework Cocoa')
	datadir = installdatadir
	build_dir = 'macosx'
	osspecificsrc = Split("""Mac/SDLMain.m""")
else:
	print "Compiling for Unix/Posix/Linux Environment"
	env = Environment(ENV = os.environ)
	env.Append(CPPPATH = ['/usr/include/SDL', '/usr/include/GL'])
	libpath = ['/usr/X11R6/lib']
	gllibs = ['GL', 'GLU']
	sdllibs = ['SDL', 'SDL_image']
	env.Append(CCFLAGS = '-Wall -g -O2 `sdl-config --cflags`')
	datadir = installdatadir
	build_dir = 'linux'
	# check for broken libGL, ignore undefined symbols then
	if (os.system('grep glBindProgram /usr/include/GL/gl*.h > /dev/null') == 0):
		if (os.system('grep glBindProgram /usr/X11R6/lib/libGL.so > /dev/null') != 0):
			print 'GL headers declare glBindProgram, but libGL.so has no such symbol! Ignoring all undefined symbols...'
			# I'm not sure which option will hopefully fix the problem... so i use both...
			env.Append(LINKFLAGS = '--unresolved-symbols=ignore-all')
			env.Append(LINKFLAGS = '-Xlinker --unresolved-symbols -Xlinker ignore-all')

###### optionally change install and data dirs
if ARGUMENTS.get('datadir', 0):
	datadir = ARGUMENTS.get('datadir', 0)

print 'Install binary path: ' + installbindir
print 'Install data path: ' + installdatadir
print 'Using data dir: ' + datadir

target_dir = '#build' + os.sep + build_dir
source_base_dir = 'src'

################ configure
conf = Configure(env)
if not conf.CheckCHeader('gl.h'):
	print 'GL library must be installed!'
	Exit(1)
if not conf.CheckCHeader('glu.h'):
	print 'GLU library must be installed!'
	Exit(1)
if not conf.CheckCHeader('SDL.h'):
	print 'SDL library must be installed!'
	Exit(1)
if not conf.CheckCHeader('SDL_image.h'):
	print 'SDL_image library must be installed!'
	Exit(1)
if not conf.CheckCHeader('SDL_net.h'):
	print 'SDL_net library is needed for network code!'
	Exit(1)
if not conf.CheckCHeader('SDL_mixer.h'):
	print 'SDL_mixer library is needed for sound support!'
	Exit(1)
if not conf.CheckCHeader('fftw3.h'):
	print 'fftw3 library must be installed!'
	Exit(1)
if conf.CheckLibWithHeader('fftw3f', 'fftw3.h', 'c'):
	print 'fftw3 library supports float type. Using it...'
	fftwlib = 'fftw3f'
	conf.env.Append(CPPFLAGS = '-DWITH_FLOAT_FFTW')

env = conf.Finish()

######################### source file lists
gfxlibs = ['oglext'] + gllibs + sdllibs
alllibs = ['dftdmedia', 'tinyxml'] + gfxlibs + ['SDL_mixer', 'SDL_net', fftwlib]

################ helper functions
def all_entries_that_start_with(list, prefix):
	list2 = []
	for i in list:
		if i.startswith(prefix):
			list2 += [i]
	return list2


################ show some help when running scons -h
Help("""
	Danger from the Deep, SConstruct file help:
	Type 'scons' to build the binary.
	Type 'scons -c' to clean up.
	Type 'scons install' to install the game (as root).
	Type 'scons tarball' to build a tarball of the source (works only with Linux).
	""")

################ build
libpath = libpath + [target_dir]
env.Append(LIBPATH = libpath)

f = open('files.txt')
allcvsfilesr = f.readlines()
# remove return code '\n' from end of line
allcvsfiles = []
for i in allcvsfilesr:
	allcvsfiles += [i[:len(i)-1]]

datafiles = all_entries_that_start_with(allcvsfiles, './data')

Export('env', 'gfxlibs', 'alllibs', 'installbindir', 'installdatadir', 'datadir', 'datafiles', 'version', 'osspecificsrc')

SConscript(source_base_dir + os.sep + 'SConscript', build_dir = target_dir, duplicate = 0)

BuildDir(target_dir, source_base_dir, duplicate=0)

############### option so that "scons tarball" builds a tarball of source and data
# tar building works only on linux
if build_dir == 'linux':
	basetarfilename = 'dangerdeep-' + version
	os.system('rm -f ' + basetarfilename)
	os.system('ln -s . ' + basetarfilename)
	filestopack = []
	for i in allcvsfiles:
		if not(i.endswith('.xcf')):
			if not(i.startswith('.' + os.sep + 'build')):
				filestopack += [basetarfilename + os.sep + i]
	env.Append(TARFLAGS = '-zh')
	env.Append(TARSUFFIX = '.gz')
	tgz = env.Tar(basetarfilename, filestopack)
	env.Alias('tarball', tgz)

#also env.Zip is possible...

# fixme: maybe try env.MSVSProject(...) to create MS VS project files

############# eof
